
services:
  din-caddy:
    image: bpi/din-caddy:stack
    restart: always
    volumes:
      - din-caddy-data:/srv
      - din-caddy-config:/etc/caddy:ro
    ports:
      - 8000 # @stack http-proxy

volumes:
  din-caddy-data:
  din-caddy-config:
