version: "1.1"
name: din-caddy
description: "din-caddy"
repos:
  - bozemanpass/din-caddy-stack@telackey/pr23
containers:
  - name: bpi/din-caddy
    ref: bozemanpass/din-caddy-stack@telackey/pr23
    path: container-build/bpi-din-caddy
pods:
  - name: din-caddy
    repository: bozemanpass/din-caddy-stack@telackey/pr23
    path: din-caddy
