name: din-caddy
description: "din-caddy"
containers:
  - name: bpi/din-caddy
    ref: bozemanpass/din-caddy-stack
    path: container-build/bpi-din-caddy
pods:
  - name: din-caddy
    repository: bozemanpass/din-caddy-stack
    path: din-caddy
