version: "1.1"
name: din-caddy
description: "din-caddy"
repos:
  - github.com/DIN-center/din-caddy-plugins
  - github.com/bozemanpass/din-caddy-stack
containers:
  - bpi/din-caddy
pods:
  - name: din-caddy-stack
    repository: bozemanpass/din-caddy-stack
    path: din-caddy
